### ISSUE TITLE
Typos and inconsistencies

### ISSUE THREAD

**Issue by QuCMGisaia** [gisaia/ARLAS-wui-builder#727]
Analytics:
- [x] When creating an analytics's widget, the capitalisation of the different widgets is different
- [x] Powerbars when at the left of a group have an inconsistent gap to the left compared to other widgets
- [x] The legend of the y-axis metric choice in histograms has a bullet point and is not capitalised, thus being inconsistent with other legends
- [x] When editing the rendering of an histogram, the selection of the histogram type is not consistent with the one of timelines
- [x] The French translation of "powerbars" is not set

Timeline:
- [x] In the Render tab of the Timeline, the explanation of the Histogram type does not include *curve*

Map:
- [x] When customising the colour palette, the numbers shown overflow from the sliding circle, and can create an horizontal scrolling bar
- [x] #837
- [x] The legend of the cluster color palette in a preview is inconsistent in writing count: *count_* when normalised, *count* when not (cf [this issue](https://github.com/gisaia/ARLAS-wui/issues/554))
- [x] In the displayed legends of color palettes, *normalized* should be spelled *normalised* to be consistent with the normalise toggle of the builder (cf [this issue](https://github.com/gisaia/ARLAS-wui/issues/554))
- [x] gisaia/ARLAS-wui#550
- [x] The comment next to the Stroke selection i the Style tab is not consistent with others (bullet point and gap up top)
- [x] When creating a cluster layer, the comment for the geometry cluster shape has typos (Recatangle) and has rectangle instead of Polygon
- [x] The names of the form fields are not consistent regarding their capitalisation
- [x] In French the column indicationg the number of elements is "Nb éléments" and could be "Nombre d'éléments"
- [x] Inconsistent French translation when editing the opacity of an element -> In the info side box refers to transparency and on the slider to opacity.
- [x] Fixed opacity is not translated in French

Look 'n feel:
- [x]  Legend of the Display spinners toggle is in French
- [x] Permet d'afficher un cercle *animée* lors du rechargement des widgets sur les données sélectionnées -> *animé*

**Comment by QuCMGisaia** [comment]
All the issues have been fixed, closing the issue.
